from Tkinter import *
root=Tk()
root.title('Movie Database')
import sqlite3
con=sqlite3.Connection("LifeinCinema_Database")
cur=con.cursor()
cur.execute("create table if not exists Rom(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Crm(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Mys(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Thr(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Com(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Dra(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Act(mname varchar(30),rating int,dname varchar(25))")
cur.execute("create table if not exists Hrm(mname varchar(30),rating int,dname varchar(25))")
def Done():
    con.commit()
    root.destroy()
def Act():
    def InsertAct():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Act values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Act")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Action movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertAct).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Rom():
    def InsertRom():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Rom values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Rom")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Romantic movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertRom).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Com():
    def InsertCom():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Com values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Com")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Comedy movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertCom).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Mys():
    def InsertMys():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Mys values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Mys")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Mystery movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertMys).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Thr():
    def InsertThr():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Thr values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Thr")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Thriller movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertThr).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Crm():
    def InsertCrm():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Crm values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Crm")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")
    root1=Tk()
    root1.title('Insert Crime movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertCrm).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
def Dra():
    def InsertDra():
        k1=a.get()
        k2=b.get()
        k3=c.get()
        k=(k1,k2,k3)
        cur.execute("Insert into Dra values(?,?,?)",k)
        root1.destroy()
    def Show_All():
        root=Tk()
        canvas = Canvas(root, borderwidth=0, background="#ffffff")
        frame = Frame(canvas, background="#ffffff")
        vsb = Scrollbar(root, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        canvas.create_window((4,4), window=frame, anchor="nw", 
                                  tags="frame")
        def onFrameConfigure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        frame.bind("<Configure>",onFrameConfigure)
        def data():
            cur.execute("select * from Dra")
            m=cur.fetchall()
            Label(frame,text='Movie name').grid(row=0,column=0)
            Label(frame,text='Rating').grid(row=0,column=1)
            Label(frame,text="Director's Name").grid(row=0,column=2)
            j=1
            for i in m:
                Label(frame,text=i[0],bg='white').grid(row=j,column=0)
                Label(frame,text=i[1],bg='white').grid(row=j,column=1)
                Label(frame,text=i[2],bg='white').grid(row=j,column=2)
                j=j+1
        data()
        #root.geometry("500x500")

    root1=Tk()
    root1.title('Insert Drama movie in Database.')
    Label(root1,text='').pack()
    Label(root1,text='Enter the movie name:').pack()
    a=Entry(root1)
    a.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the rating you give to the movie:').pack()
    b=Entry(root1)
    b.pack()
    Label(root1,text='').pack()
    Label(root1,text='Enter the name of the director:').pack()
    c=Entry(root1)
    c.pack()
    Label(root1,text='').pack()
    Button(root1,text='Insert',bg='blue',fg='black',activebackground='green',activeforeground='grey',command=InsertDra).pack()
    Button(root1,text='Show All',fg='white',bg='Black',command=Show_All).pack()
Label(root,text='').pack()
Label(root,text='').pack()
Label(root,text='Hello Sir. Welcome to your Movie Database.').pack()
Label(root,text='').pack()
Label(root,text='Choose the genre in which you want to enter your movie').pack()
Label(root,text='').pack()
Label(root,text='').pack()
Button(root,text='Action',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Act).pack()
Label(root,text='').pack()
Button(root,text='Drama',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Dra).pack()
Label(root,text='').pack()
Button(root,text='Romance',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Rom).pack()
Label(root,text='').pack()
Button(root,text='Crime',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Crm).pack()
Label(root,text='').pack()
Button(root,text='Thriller',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Thr).pack()
Label(root,text='').pack()
Button(root,text='Comedy',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Com).pack()
Label(root,text='').pack()
Button(root,text='Mystery',width=20,height=2,font="Comic 10 bold",bg='Orange',command=Mys).pack()
Label(root,text='').pack()
Label(root,text='If you are done Sir. Press Done to save your work. Thank you.').pack()
Label(root,text='').pack()
Button(root,text='Done',width=20,height=2,font="Comic 10 bold",bg='Green',command=Done).pack()
Label(root,text='').pack()
mainloop()
